#!/usr/bin/ruby
# -*- ruby -*-

require 'optparse'

# Class taken from Rails 3.0.9, it's the same thing that does rake notes.
# I extended it to include HAML files.
class SourceAnnotationExtractor
  class Annotation < Struct.new(:line, :tag, :text)

    # Returns a representation of the annotation that looks like this:
    #
    #   [126] [TODO] This algorithm is simple and clearly correct, make it faster.
    #
    # If +options+ has a flag <tt>:tag</tt> the tag is shown as in the example above.
    # Otherwise the string contains just line and text.
    def to_s(options={})
      s = "[<a target='_blank' class='pnlinenum' href='%s/%s#L%d'>%3d</a>] " % [options[:url], options[:file], line, line]
      s << "[#{tag}] " if options[:tag]
      s << text
    end
  end

  # Prints all annotations with tag +tag+ under the root directories +app+, +lib+,
  # and +test+ (recursively). Only filenames with extension +.builder+, +.rb+,
  # +.rxml+, +.rjs+, +.rhtml+, or +.erb+ are taken into account. The +options+
  # hash is passed to each annotation's +to_s+.
  #
  # This class method is the single entry point for the rake tasks.
  def self.enumerate(tag, options={})
    extractor = new(tag)
    extractor.display(extractor.find(options[:dirs]), options)
  end

  attr_reader :tag

  def initialize(tag)
    @tag = tag
  end

  # Returns a hash that maps filenames under +dirs+ (recursively) to arrays
  # with their annotations. Only files with annotations are included, and only
  # those with extension +.builder+, +.rb+, +.rxml+, +.rjs+, +.rhtml+, and +.erb+
  # are taken into account.
  def find(dirs=%w(app lib test))
    dirs.inject({}) { |h, dir| h.update(find_in(dir)) }
  end

  # Returns a hash that maps filenames under +dir+ (recursively) to arrays
  # with their annotations. Only files with annotations are included, and only
  # those with extension +.builder+, +.rb+, +.rxml+, +.rjs+, +.rhtml+, and +.erb+
  # are taken into account.
  def find_in(dir)
    results = {}

    Dir.glob("#{dir}/*") do |item|
      next if File.basename(item)[0] == ?.

      if File.directory?(item)
        results.update(find_in(item))
      elsif item =~ /\.(haml|builder|(r(?:b|xml|js)))$/
        results.update(extract_annotations_from(item, /#\s*(#{tag}):?\s*(.*)$/))
      elsif item =~ /\.(rhtml|erb)$/
        results.update(extract_annotations_from(item, /<%\s*#\s*(#{tag}):?\s*(.*?)\s*%>/))
      end
    end

    results
  end

  # If +file+ is the filename of a file that contains annotations this method returns
  # a hash with a single entry that maps +file+ to an array of its annotations.
  # Otherwise it returns an empty hash.
  def extract_annotations_from(file, pattern)
    lineno = 0
    result = File.readlines(file).inject([]) do |list, line|
      lineno += 1
      next list unless line =~ pattern
      list << Annotation.new(lineno, $1, $2)
    end
    result.empty? ? {} : { file => result }
  end

  # Prints the mapping from filenames to annotations in +results+ ordered by filename.
  # The +options+ hash is passed to each annotation's +to_s+.
  def display(results, options={})
    results.keys.sort.each do |file|
      puts "!<a target='_blank' class='pnfilelink' href='#{options[:url]}/#{file}'>#{file}</a>:"
      options[:file] = file
      results[file].each do |note|
        puts "! #{options[:tag_map][note.tag] || '!!'} #{note.to_s(options)}"
      end
      puts
    end
  end
end

@redmine_host = "https://dev.spawn.vc"
@redmine_project_id = nil

opts = OptionParser.new do |o|
  o.program_name = 'setup_build'
  o.separator 'Options:'
  o.on('--redmine-host HOST', nil, 'Redmine host') { |@redmine_host| }
  o.on('--project-id ID', '', 'Redmine project id') { |@redmine_project_id| }

  o.on_tail('--help', '-h', 'Show this message') do
    puts " -- error running setup build"
    puts opts
    exit 1
  end
end
opts.parse!(ARGV)

if @redmine_project_id.nil?
  puts " -- error, redmine project id was nil: set --project-id XXX option"
  exit 1
end

## /projects/bigtuna/repository/revisions/baf34364e07e79b7531ef84641a701ee74807f97/entry/config/deploy.rb
@build_path = ARGV[0] || Dir.pwd
Dir.chdir(@build_path)

@git_revision = `git log | head -1 | awk '// { print $2 }'`.strip
puts "! == Git revision <a target='_blank' class='pnrevlink' href='%s/projects/%s/repository/revisions/%s'>%s</a>" % [@redmine_host, @redmine_project_id, @git_revision, @git_revision]
puts ""

@redmine_url_base = "%s/projects/%s/repository/revisions/%s/entry" % [ @redmine_host,
                                                                       @redmine_project_id,
                                                                       @git_revision]
SourceAnnotationExtractor.
  enumerate("OPTIMIZE|FIXME|TODO", {
              :tag => true,
              :url => @redmine_url_base,
              :dirs => (Dir['*/'].map{ |a| a[0..-2] } -
                        ["script","public","db","doc","log","tmp","vendor"]),
              :tag_map => {
                "TODO" => "==",
                "FIXME" => "!!",
                "OPTIMIZE" => "**",
              }})
